version: "3"
services:
  sql:
    image: albiondata/sql:latest
    restart: on-failure
    command: "-n 'nats://${NATS_USER}:${NATS_PWD}@nats:4222' -s 'server=mysql;port=3306;database=${MYSQL_DB};user=${MYSQL_USER};password=${MYSQL_PWD}' -d"
    depends_on: 
      - mysql
      - nats
    networks: 
      - albiondata
  api:
    image: albiondata/api:latest
    restart: on-failure
    command: "-s 'server=mysql;port=3306;database=${MYSQL_DB};user=${MYSQL_USER};password=${MYSQL_PWD}' -d"
    ports:
      - 8056:80
    depends_on: 
      - mysql
    networks: 
      - albiondata
  gate:
    image: albiondata/gate:latest
    restart: on-failure
    environment:
      ENABLE_NATS: 1
      NATS_URI: nats://${NATS_USER}:${NATS_PWD}@nats:4222
      POW_DIFFICULITY: 37
      POW_PORT: 4223      
    ports:
      - 4223:4223
    depends_on: 
      - nats
    networks: 
      - albiondata
  deduper:
    image: albiondata/deduper:latest
    restart: on-failure
    command: "-o nats://${NATS_USER}:${NATS_PWD}@nats:4222 -n 'nats://${NATS_USER}:${NATS_PWD}@nats:4222' -r 'redis:6379' -d"
    depends_on: 
      - nats
      - redis
    networks: 
      - albiondata
  nats:
    image: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    command: "--user ${NATS_USER} --pass ${NATS_PWD}"
    networks: 
      - albiondata
  mysql:
    image: mariadb:10.5.10
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_PWD}
    ports:
      - 3306:3306
    volumes:
      - ./mysqldata:/var/lib/mysql
    networks: 
      - albiondata
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    command: redis-server --appendonly yes
    networks: 
      - albiondata
  proxy:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    environment:
      X_FRAME_OPTIONS: "sameorigin"
      DB_SQLITE_FILE: "/data/database.sqlite"
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./nginx_proxy_manager/data:/data
      - ./nginx_proxy_manager/letsencrypt:/etc/letsencrypt
    networks: 
      - albiondata
  nginx:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    environment:
      - X_FRAME_OPTIONS="sameorigin"
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./nginx_proxy_manager/data:/data
      - ./nginx_proxy_manager/letsencrypt:/etc/letsencrypt
    networks: 
      - albiondata
  nginx:
    image: nginx
    volumes:
      - "$PWD/web:/usr/share/nginx/html:ro"
    ports:
      - 8080:80        
networks:
  albiondata: